In [1]:
import numpy as np
from sympy import *
init_printing()

In [2]:
arr=np.array([[10,   12,  14,  16,  18,  20,  22,  24], 
              [39.7,30.9,24.9,20.5,17.5,15.1,13.1,11.6]])

In [3]:
X=sum(np.log(arr[0]))
display(arr[0])
display(np.log(arr[0]))
X

array([10., 12., 14., 16., 18., 20., 22., 24.])

array([2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176,
       2.99573227, 3.09104245, 3.17805383])

In [4]:
Y=sum(np.log(arr[1]))
Y

In [5]:
Xsqured=sum(np.power(np.log(arr[0]),2))
Xsqured

In [6]:
XY=sum(np.log(arr[0])*np.log(arr[1]))
XY

In [7]:
a,b=symbols('a b')
eq1=Eq(a*Xsqured+b*X,XY)
eq2=Eq(a*X+b*8,Y)
A,B=solve([eq1,eq2]).values()
A,B

In [8]:
p,v,c=symbols('P V C')
Eq(p*(v**-A),c)

In [9]:
arr=np.array([[  30,    45,   60]
              ,[0.225, 0.27, 0.52]])
arr

array([[30.   , 45.   , 60.   ],
       [ 0.225,  0.27 ,  0.52 ]])

In [10]:
Y=1/arr[1]
Y

array([4.44444444, 3.7037037 , 1.92307692])

In [11]:
X=np.cos(arr[0] * np.pi / 180.)
X

array([0.8660254 , 0.70710678, 0.5       ])

In [12]:
Xsq=np.power(X,2)
Xsq

array([0.75, 0.5 , 0.25])

In [13]:
XY=X*Y
XY

array([3.84900179, 2.618914  , 0.96153846])

In [14]:
print(sum(Y),sum(X),sum(Xsq),sum(XY))
a,b=symbols('a b')
eq1=Eq(a*sum(Xsq)+b*sum(X),sum(XY))
eq2=Eq(a*sum(X)+b*4,sum(Y))
print(eq1)
print(eq2)
A,B=solve([eq1,eq2]).values()
A,B

10.071225071225072 2.0731321849709863 1.5000000000000004 7.429454260530587
Eq(1.5*a + 2.07313218497099*b, 7.42945426053059)
Eq(2.07313218497099*a + 4*b, 10.0712250712251)
