In [1]:
from sympy import *
import numpy as np
init_printing() #fancy printing
x,y,z=symbols("x y z")
def simpsonRule(a,b,h,problem,var):
    print(problem)
    problem=lambdify(y, problem, "numpy")
    arr=np.arange(a,b,h)
    print(arr)
    problem=problem(arr)
    print(problem)
    odds=problem[1:-1:2]
    evens=problem[2:-1:2]
    integralValue=(h/3)*(problem[0]+problem[-1]+4*sum(odds)+2*sum(evens))
    return integralValue
def trapozidalRule(a,b,h,problem,var):
    print(problem)
    problem=lambdify(y, problem, "numpy")
    arr=np.arange(a,b,h)
    problem=problem(arr)
    print(problem)
    #print(problem[1:-1])
    integralValue=(h/2)*(problem[0]+problem[-1]+2*sum(problem[1:-1]))
    return integralValue

In [10]:
h=0.75
a=0
b=9/2
problem1=simplify(y**3*sin(y))
#simpsonRule(a,b,h,problem1,y)
trapozidalRule(a,b,h,problem1,y)

y**3*sin(y)
[  0.           0.28756635   3.36654558   8.86274001   3.81024022
 -30.14092892]


In [12]:
a=0
b=np.pi/2
n=4
h=(b-a)/n
problem2=simplify(1/(sqrt(1-(0.25*sin(y)))))
#simpsonRule(a,b,h,problem2,y)
trapozidalRule(a,b,h,problem2,y)

1/sqrt(-0.25*sin(y) + 1)
[1.         1.05156649 1.10215118 1.14032416]


In [17]:
h=10
problem3=np.array([0,4,7,9,12,15,14,8,3])
odds=problem3[1:-1:2]
evens=problem3[2:-1:2]
integralValue=(h/3)*(problem3[0]+problem3[-1]+4*sum(odds)+2*sum(evens))
tar=(h/2)*(problem3[0]+problem3[-1]+2*sum(problem3[1:-1]))
#integralValue
tar

In [15]:
a=0
b=2
n=8
h=(b-a)/n
problem4=simplify(y*(sqrt(8-y**3)))
simpsonRule(a,b,h,problem4,y)
#trapozidalRule(a,b,h,problem4,y)

y*sqrt(-y**3 + 8)
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75]
[0.         0.70641591 1.40312152 2.06462958 2.64575131 3.07379931
 3.22587198 2.84375   ]


In [6]:
a=0
b=2
h=0.2
problem6=simplify(ln(2*y**2+1))
simpsonRule(a,b,h,problem6,y)
#trapozidalRule(a,b,h,problem6,y)

log(2*y**2 + 1)
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[0.         0.07696104 0.27763174 0.54232429 0.82417544 1.09861229
 1.35583515 1.59330853 1.8115621  2.01223279]
